version: '3'

services:

  database:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gympoint
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data

  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo/data:/data/db
